from typing import Protocol

class Memory(Protocol):
    def history(self, user: str) -> list[dict]: ...
    def append(self, user: str, role: str, text: str) -> None: ...
    def forget(self, user: str) -> None: ...

class Catalog(Protocol):
    async def execute(self, name: str, arguments: dict) -> dict: ...

class LanguageModel(Protocol):
    async def reply(self, messages: list[dict], catalog: Catalog) -> str: ...
